src/main/java/com/kuirado/models/DifficultyLevel.java
package com.kuirado.models;

public enum DifficultyLevel {
    EASY("łatwy"),
    MEDIUM("średni"),
    HARD("trudny");

    private final String text;

    DifficultyLevel(String text) {
        this.text = text;
    }

    public String getText() {
        return this.text;
    }

    public String getName() {
        return this.name();
    }

}

src/main/java/com/kuirado/models/Ingredient.java
package com.kuirado.models;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@Entity
@Table(name = "ingredient")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Ingredient.findAll", query = "SELECT i FROM Ingredient i"),
    @NamedQuery(name = "Ingredient.findById", query = "SELECT i FROM Ingredient i WHERE i.id = :id"),
    @NamedQuery(name = "Ingredient.findByName", query = "SELECT i FROM Ingredient i WHERE i.name = :name"),
    @NamedQuery(name = "Ingredient.findByCategory", query = "SELECT i FROM Ingredient i WHERE i.category = :category")})
public class Ingredient implements Serializable {

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "ingredientId")
    private Collection<FkRecipeIngredient> fkRecipeIngredientCollection;

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 32)
    @Column(name = "category")
    private String category;

    public Ingredient() {
    }

    public Ingredient(Integer id) {
        this.id = id;
    }

    public Ingredient(Integer id, String name, String category) {
        this.id = id;
        this.name = name;
        this.category = category;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategoryValue() {
        return IngredientCategory.valueOf(this.category).getText();
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Ingredient)) {
            return false;
        }
        Ingredient other = (Ingredient) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.kuirado.models.Ingredient[ id=" + id + " ]";
    }

    @XmlTransient
    public Collection<FkRecipeIngredient> getFkRecipeIngredientCollection() {
        return fkRecipeIngredientCollection;
    }

    public void setFkRecipeIngredientCollection(Collection<FkRecipeIngredient> fkRecipeIngredientCollection) {
        this.fkRecipeIngredientCollection = fkRecipeIngredientCollection;
    }

}

src/main/java/com/kuirado/models/IngredientCategory.java
package com.kuirado.models;

public enum IngredientCategory {
    FRUITS("owoce"),
    VEGETABLES("warzywa"),
    DAIRY_PRODUCTS("nabiał");

    private final String text;

    IngredientCategory(String text) {
        this.text = text;
    }

    public String getText() {
        return this.text;
    }

    public String getName() {
        return this.name();
    }
}

src/main/java/com/kuirado/models/Recipe.java
package com.kuirado.models;

import java.io.Serializable;
import java.util.Collection;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@Entity
@Table(name = "recipe")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Recipe.findAll", query = "SELECT r FROM Recipe r"),
    @NamedQuery(name = "Recipe.findById", query = "SELECT r FROM Recipe r WHERE r.id = :id"),
    @NamedQuery(name = "Recipe.findByName", query = "SELECT r FROM Recipe r WHERE r.name = :name"),
    @NamedQuery(name = "Recipe.findByPreparationTime", query = "SELECT r FROM Recipe r WHERE r.preparationTime = :preparationTime"),
    @NamedQuery(name = "Recipe.findByDifficultyLevel", query = "SELECT r FROM Recipe r WHERE r.difficultyLevel = :difficulty_level")
})
public class Recipe implements Serializable {

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "recipeId")
    private Collection<FkRecipeIngredient> fkRecipeIngredientCollection;

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;
    @Basic(optional = false)
    @NotNull
    @Lob
    @Size(min = 1, max = 65535)
    @Column(name = "description")
    private String description;
    @Basic(optional = false)
    @NotNull
    @Column(name = "preparationTime")
    private int preparationTime;
    @JoinTable(name = "recipe_tag", joinColumns = {
        @JoinColumn(name = "recipe_id", referencedColumnName = "id")}, inverseJoinColumns = {
        @JoinColumn(name = "tag_id", referencedColumnName = "id")})
    @ManyToMany
    private Set<Tag> tagSet;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "recipeId")
    private Collection<FkRecipeIngredient> ingredientSet;
    @Column(name = "difficulty_level")
    private String difficultyLevel;

    public Recipe() {
    }

    public Recipe(Integer id) {
        this.id = id;
    }

    public Recipe(Integer id, String name, String description, int preparationTime, String difficultyLevel) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.preparationTime = preparationTime;
        this.difficultyLevel = difficultyLevel;
    }

    public String getDifficultyLevel() {
        return difficultyLevel;
    }

    public void setDifficultyLevel(String difficultyLevel) {
        this.difficultyLevel = difficultyLevel;
    }

    public String getDifficultyLevelValue() {
        return DifficultyLevel.valueOf(this.difficultyLevel).getText();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getPreparationTime() {
        return preparationTime;
    }

    public void setPreparationTime(int preparationTime) {
        this.preparationTime = preparationTime;
    }

    @XmlTransient
    public Set<Tag> getTagSet() {
        return tagSet;
    }

    public void setTagSet(Set<Tag> tagSet) {
        this.tagSet = tagSet;
    }

    @XmlTransient
    public Collection<FkRecipeIngredient> getIngredientSet() {
        return ingredientSet;
    }

    public void setIngredientSet(Collection<FkRecipeIngredient> ingredientSet) {
        for (FkRecipeIngredient i : ingredientSet) {
            i.setRecipeId(this);
        }
        this.ingredientSet = ingredientSet;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Recipe)) {
            return false;
        }
        Recipe other = (Recipe) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.kuirado.model.Recipe[ id=" + id + " ]";
    }

    @XmlTransient
    public Collection<FkRecipeIngredient> getFkRecipeIngredientCollection() {
        return fkRecipeIngredientCollection;
    }

    public void setFkRecipeIngredientCollection(Collection<FkRecipeIngredient> fkRecipeIngredientCollection) {
        this.fkRecipeIngredientCollection = fkRecipeIngredientCollection;
    }

}

src/main/java/com/kuirado/controllers/HomeController.java
package com.kuirado.controllers;

import com.kuirado.utils.ModelAndViewFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class HomeController {

    @Autowired
    ModelAndViewFactory modelAndViewFactory;

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView home() {
        return modelAndViewFactory.getModelAndView("home");
    }
}

src/main/java/com/kuirado/controllers/IngredientAdminController.java
package com.kuirado.controllers;

import com.kuirado.models.Ingredient;
import com.kuirado.services.IngredientService;
import com.kuirado.utils.ModelAndViewFactory;
import com.kuirado.utils.PhotoManager;
import java.io.IOException;
import java.util.LinkedList;
import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class IngredientAdminController {

    @Autowired
    private IngredientService ingredientService;

    @Autowired
    private PhotoManager photoManager;

    @Autowired
    ModelAndViewFactory modelAndViewFactory;

    @RequestMapping(value = "/Admin/Ingredient", method = RequestMethod.GET)
    protected ModelAndView editIngredient(HttpServletRequest request) throws IOException {

        String id = request.getParameter("id");
        if (id != null) {
            int parsedId = Integer.parseInt(id);
            //    request.setAttribute("ingredientPhoto",  photoManager.getPhoto("ingredient/" + id));
            Ingredient ingredient = ingredientService.getIngredient(parsedId);
            request.setAttribute("ingredient", ingredient);
        }
        request.setAttribute("ingredientCategories", ingredientService.getIngredientCategory());
        return modelAndViewFactory.getModelAndView("ingredientAdd");
    }

    @RequestMapping(value = "/Admin/Ingredient", method = RequestMethod.POST)
    protected ModelAndView addIngredient(HttpServletRequest request,
            @RequestParam("ingredientPhoto") MultipartFile ingredientPhoto) throws IOException {
        String name = request.getParameter("name");
        String category = request.getParameter("category");
        String id = request.getParameter("id");

        LinkedList<String> errors = new LinkedList<>();

        if (name.equals("") || category.equals("")) {
            errors.add("Wszytskie pola muszą być wypełnione");
        }

        if (!ingredientService.isNameAllowed(name, parseId(id))) {
            errors.add("Składnik już istnieje");
        }

        if (errors.size() > 0) {
            ModelAndView model = modelAndViewFactory.getModelAndView("ingredientAdd");
            model.addObject("errors", errors);
            return model;
        } else {
            if (id.length() > 0) {
                int parsedId = Integer.parseInt(id);
                ingredientService.updateIngredient(parsedId, name, category);
            } else {
                int parsedId = ingredientService.addIngredient(name, category);
                id = Integer.toString(parsedId);
            }
        }
        if (!ingredientPhoto.isEmpty()) {
            photoManager.savePhoto(ingredientPhoto, "ingredient/" + id);
        }
        return new ModelAndView("redirect:../Ingredient");
    }

    @RequestMapping(value = "/Admin/Ingredient", method = RequestMethod.DELETE)
    public ModelAndView removeIngredient(HttpServletRequest request) throws IOException {
        int id = Integer.parseInt(request.getParameter("id"));
        photoManager.removePhoto("ingredient/" + request.getParameter("id"));
        ingredientService.removeIngredient(id);
        return new ModelAndView("redirect:../Ingredient");
    }

    private int parseId(String possibleId) {
        try {
            return Integer.valueOf(possibleId);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
}

src/main/java/com/kuirado/controllers/IngredientController.java
package com.kuirado.controllers;

import com.kuirado.services.IngredientService;
import com.kuirado.utils.ModelAndViewFactory;
import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class IngredientController {

    @Autowired
    private IngredientService ingredientService;

    @Autowired
    ModelAndViewFactory modelAndViewFactory;

    @RequestMapping(value = "/Ingredient", method = RequestMethod.GET)
    public ModelAndView showIngredients(HttpServletRequest request) {
        request.setAttribute("ingredients", ingredientService.getIngredients());
        return modelAndViewFactory.getModelAndView("ingredient");
    }
}

src/main/java/com/kuirado/controllers/LogoutController.java
package com.kuirado.controllers;

import com.kuirado.models.User;
import com.kuirado.services.UserService;
import com.kuirado.utils.ModelAndViewFactory;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class LogoutController {

    @Autowired
    private UserService userService;

    @RequestMapping(value = "/Logout", method = RequestMethod.GET)
    public ModelAndView form(HttpServletRequest request, HttpServletResponse response) {
        Cookie[] cookies = request.getCookies();
        if (cookies != null) {
            for (Cookie cookie : cookies) {
                if (cookie.getName().equals("remember-me")) {
                    userService.presistanceLoginRemoveUser(cookie.getValue());
                    cookie.setValue("");
                    cookie.setPath("/");
                    cookie.setMaxAge(0);
                    response.addCookie(cookie);
                }
            }
        }
        request.getSession().invalidate();
        return new ModelAndView("redirect:./");
    }

}

src/main/webapp/views/home.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<h1>Strona główna</h1>

src/main/webapp/views/ingredient.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<table>
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Category</td>
        <td>Photo</td>
        <td>Actions</td>
    </tr>
    <c:forEach items="${ingredients}" var="ingredient">
        <tr>
            <td>${ingredient.id}</td>
            <td class="ingredient-name" name="name">${ingredient.name}</td>
            <td>${ingredient.categoryValue}</td>
            <td><img src="photos/ingredient/${ingredient.id}" width="100"></td>
            <td>
                <a href="<c:url value="/Admin/Ingredient"></c:url>?id=${ingredient.id}" class="btn btn-primary edit-button">Edytuj</a>
                <form method="POST" action="<c:url value="/Admin/Ingredient"></c:url>">
                    <input name="_method" type="hidden" value="delete">
                    <input type="hidden" name="id" value="${ingredient.id}">
                    <button class="btn btn-danger delete-button">Usuń</button>
                </form>
            </td>
        </tr>
    </c:forEach>
</table>

src/main/webapp/views/ingredientAdd.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<form method="POST" enctype="multipart/form-data">
    <input type="hidden" name="id" value="${ingredient.id}">
    <label>Nazwa</label>
    <input name="name" class="form-control" value="${ingredient.name}">
    <label>Kategoria</label>
    <select name="category" class="form-control">
        <c:forEach items="${ingredientCategories}" var="ingredientCategory">
            <option value="${ingredientCategory.name}" <c:if test="${ingredient.category == ingredientCategory.name}">selected=""</c:if>>${ingredientCategory.text}</option>
        </c:forEach>           
    </select>
    <label>Zdjęcie</label><br/>
     <c:if test="${ingredient.id != null}">
         <img src="../photos/ingredient/${ingredient.id}" width="100">
    </c:if>
    <input name="ingredientPhoto" type="file" class="form-control">
        <button id="add-ingredient-button" class="btn btn-primary">Dodaj</button>
</form>

src/main/webapp/views/login.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<form method="POST">
    <label>Email</label>
    <input name="email" class="form-control">
    <label>Hasło</label>
    <input name="password" type="password" class="form-control">
    <tr>
        <td>Remember Me:</td>
        <td><input type="checkbox" name="remember-me" /></td>
    </tr>
    <button id="login-button" class="btn btn-primary">Zaloguj się</button>
</form>

src/main/webapp/views/recipe.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<table>
    <tr>
        <td>Name</td>
        <td>Description</td>
        <td>Preparation time</td>
        <td>Difficulty</td>
        <td>Photo</td>
        <td>Ingredients</td>
        <td>Actions</td>
    </tr>
    <c:forEach items="${recipes}" var="recipe">
        <tr>
            <td>
                <c:forEach items="${recipe.tagSet}" var="tag">#${tag.name}</c:forEach>   
            </td>
        </tr>
        <tr>
            <td class="recipe-name">${recipe.name}</td>
            <td>${recipe.description}</td>
            <td>${recipe.preparationTime}</td>
            <td>${recipe.difficultyLevelValue}</td>
            <c:if test="${flag == false}">
                <td><img src="../photos/recipe/${recipe.id}" width="100"></td>
            </c:if>
            <c:if test="${flag == true}">
                <td><img src="../photos/recipe/${recipe.id}" width="100"></td>
            </c:if>
            <td>
                Składniki:
                <ul>
                    <c:forEach items="${recipe.ingredientSet}" var="ingredient">
                        <li>${ingredient.ingredient.name} ${ingredient.amount}</li>
                    </c:forEach>
                </ul>            
            </td>
            <td>
                 <a href="<c:url value="/Admin/Recipe"></c:url>?id=${recipe.id}" class="btn btn-primary edit-button">Edytuj</a>
                <form method="POST" action="<c:url value="/Admin/Recipe"></c:url>">
                    <input name="_method" type="hidden" value="delete">
                    <input type="hidden" name="id" value="${recipe.id}">
                    <button class="btn btn-danger delete-button">Usuń</button>
                </form>
            </td>
        </tr>
    </c:forEach>
</table>

src/main/webapp/views/recipeAdd.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@taglib  prefix="cfn" uri="/WEB-INF/custom-functions.tld" %>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
</head>

<form id="add-form" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="id" value="${recipe.id}">
    <label>Nazwa</label>
    <input name="name" class="form-control" value="${recipe.name}">
    <label>Opis</label>
    <input name="description" class="form-control" value="${recipe.description}">
    <label>Czas przygotowania</label>
    <input name="preparationTime" class="form-control" type="number" required="" value="${recipe.preparationTime}">
    <label>Trudność</label>
    <select name="difficultyLevel" class="form-control">
        <c:forEach items="${difficultyLevels}" var="difficultyLevel">
             <option value="${difficultyLevel.name}" <c:if test="${recipe.difficultyLevel == difficultyLevel.name}">selected=""</c:if>>${difficultyLevel.text}</option>
       </c:forEach>
    </select>
    <label>Dodaj tag do wyszukiwania przepisu</label><br/>
    <select name="tags" id="tags" class="js-example-basic-multiple" multiple="multiple">
        <c:forEach items="${allTags}" var="tag">
            <option value="${tag.name}" <c:if test="${  fn:contains( recipe.tagSet, tag ) }">selected="1"</c:if>>${tag.name}</option>
        </c:forEach>
    </select>
    <br/>
    <label>Zdjęcie</label><br/>
     <c:if test="${recipe.id != null}">
         <img src="../photos/recipe/${recipe.id}" width="100">
    </c:if>
    <input name="recipePhoto" type="file" class="form-control">
    <label>Składniki</label>
    <input type="hidden" name="ingredients" id="ingredients-field">
    <div id="ingredients-list" ></div>
    <span class="btn btn-primary" id="add-ingredient-button">Dodaj składnik</span>
    <button class="btn btn-primary" id="add-recipe-button" type="submit">Dodaj</button>
</form>
        
<script>
    var ingredients = '<select class="field" multiple="true" size="${fn:length(ingredients)}" required="">' +
        <c:forEach items="${ingredients}" var="ingredient">
            '<option value="${ingredient.id}" >${ingredient.name}</option>' +
        </c:forEach>
    '</select>' +
    '<input class="field"><br>';
    var ingredientsList = $("#ingredients-list");
    var button = $("#add-ingredient-button");
    var form = $("#add-form");
    var ingredientsField = $("#ingredients-field");
    button.click(function () {
        ingredientsList.append(ingredients);
    });
    form.submit(function () {
        var value = ingredientsList.find(".field").map(function (e, i) { return $(i).val(); }).toArray().join(",");
        ingredientsField.val(value);
    });
    $(document).ready(function() {
        $('.js-example-basic-multiple').select2({tags: true});
    });
</script>

src/main/webapp/views/register.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<form method="POST">
    <label>Email</label>
    <input name="email" class="form-control">
    <label>Hasło</label>
    <input name="password" type="password" class="form-control">
    <label>Powtórz Hasło</label>
    <input name="retype-password" type="password" class="form-control">
    <button id="register-button" class="btn btn-primary">Zarejestruj się</button>
</form>